name: dotnet publish
on:
  push:
    # publish tags and release branches
    tags:
      - "*"
    branches:
      - "release/*"
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
        dotnet-version:
          - 8.0
          - 9.0
    name: test dotnet ${{ matrix.dotnet-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - uses: daaku/gh-action-apt-install@v4
        if: RUNNER_OS == 'Linux'
        with:
          packages: graphviz
      - run: dotnet test
  publish:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet pack -o pkg
      - env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push pkg/GraphVizard*.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
