name: dotnet publish
on:
  push:
    # publish tags and release branches
    tags:
      - "*"
    branches:
      - "release/*"
jobs:
  test:
    uses: ./.github/workflows/test.yaml
  publish:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"
      - run: dotnet pack -o pkg
      - env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push pkg/GraphVizard*.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
